parameters:
#    ingetis_content.example.class: Ingetis\ContentBundle\Example

services:
#    ingetis_content.example:
#        class: %ingetis_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
