parameters:
#    ingetis_annonceindex.example.class: Ingetis\AnnonceindexBundle\Example

services:
#    ingetis_annonceindex.example:
#        class: %ingetis_annonceindex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
