parameters:
#    ingetis_coldroite.example.class: Ingetis\ColdroiteBundle\Example

services:
#    ingetis_coldroite.example:
#        class: %ingetis_coldroite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
