<?php

namespace Proxies\__CG__\Ingetis\OffresBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OffresEmplois extends \Ingetis\OffresBundle\Entity\OffresEmplois implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'idOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'titreOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'descriptionOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'vues', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'date');
        }

        return array('__isInitialized__', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'idOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'titreOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'descriptionOffre', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'vues', '' . "\0" . 'Ingetis\\OffresBundle\\Entity\\OffresEmplois' . "\0" . 'date');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OffresEmplois $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOffre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOffre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffre', array());

        return parent::getIdOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreOffre($titreOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreOffre', array($titreOffre));

        return parent::setTitreOffre($titreOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreOffre', array());

        return parent::getTitreOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionOffre($descriptionOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionOffre', array($descriptionOffre));

        return parent::setDescriptionOffre($descriptionOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionOffre', array());

        return parent::getDescriptionOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setVues($vues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVues', array($vues));

        return parent::setVues($vues);
    }

    /**
     * {@inheritDoc}
     */
    public function getVues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVues', array());

        return parent::getVues();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

}
