<?php

namespace Proxies\__CG__\Ingetis\PagesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pages extends \Ingetis\PagesBundle\Entity\Pages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'titrePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'titreNav', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'textePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'urlPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'vuesPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'lastIp', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'datePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'indexCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'indexSousCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idSousCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'pageFixe', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'urlPageFixe', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'link', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idLink', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'lastVisit', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'position');
        }

        return array('__isInitialized__', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'titrePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'titreNav', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'textePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'urlPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'vuesPage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'lastIp', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'datePage', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'indexCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'indexSousCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idSousCategorie', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'pageFixe', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'urlPageFixe', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'link', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'idLink', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'lastVisit', '' . "\0" . 'Ingetis\\PagesBundle\\Entity\\Pages' . "\0" . 'position');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPage()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPage();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPage', array());

        return parent::getIdPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitrePage($titrePage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitrePage', array($titrePage));

        return parent::setTitrePage($titrePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitrePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitrePage', array());

        return parent::getTitrePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreNav($titreNav)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreNav', array($titreNav));

        return parent::setTitreNav($titreNav);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreNav()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreNav', array());

        return parent::getTitreNav();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextePage($textePage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextePage', array($textePage));

        return parent::setTextePage($textePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextePage', array());

        return parent::getTextePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlPage($urlPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlPage', array($urlPage));

        return parent::setUrlPage($urlPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlPage', array());

        return parent::getUrlPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVuesPage($vuesPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVuesPage', array($vuesPage));

        return parent::setVuesPage($vuesPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getVuesPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVuesPage', array());

        return parent::getVuesPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastIp($lastIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastIp', array($lastIp));

        return parent::setLastIp($lastIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastIp', array());

        return parent::getLastIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePage($datePage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePage', array($datePage));

        return parent::setDatePage($datePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePage', array());

        return parent::getDatePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexCategorie($indexCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexCategorie', array($indexCategorie));

        return parent::setIndexCategorie($indexCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexCategorie', array());

        return parent::getIndexCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexSousCategorie($indexSousCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexSousCategorie', array($indexSousCategorie));

        return parent::setIndexSousCategorie($indexSousCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexSousCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexSousCategorie', array());

        return parent::getIndexSousCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorie($idCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorie', array($idCategorie));

        return parent::setIdCategorie($idCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorie', array());

        return parent::getIdCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSousCategorie($idSousCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSousCategorie', array($idSousCategorie));

        return parent::setIdSousCategorie($idSousCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSousCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSousCategorie', array());

        return parent::getIdSousCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageFixe($pageFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageFixe', array($pageFixe));

        return parent::setPageFixe($pageFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageFixe', array());

        return parent::getPageFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlPageFixe($urlPageFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlPageFixe', array($urlPageFixe));

        return parent::setUrlPageFixe($urlPageFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlPageFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlPageFixe', array());

        return parent::getUrlPageFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', array($link));

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', array());

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLink($idLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLink', array($idLink));

        return parent::setIdLink($idLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLink', array());

        return parent::getIdLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastVisit($lastVisit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastVisit', array($lastVisit));

        return parent::setLastVisit($lastVisit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastVisit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastVisit', array());

        return parent::getLastVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

}
