<?php

namespace Proxies\__CG__\Ingetis\DivindexBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DivAccueil extends \Ingetis\DivindexBundle\Entity\DivAccueil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'idDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'titreDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'lienDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'texteDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'imgDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'dateDivAccueil');
        }

        return array('__isInitialized__', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'idDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'titreDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'lienDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'texteDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'imgDivAccueil', '' . "\0" . 'Ingetis\\DivindexBundle\\Entity\\DivAccueil' . "\0" . 'dateDivAccueil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DivAccueil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDivAccueil()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDivAccueil();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDivAccueil', array());

        return parent::getIdDivAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreDivAccueil($titreDivAccueil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreDivAccueil', array($titreDivAccueil));

        return parent::setTitreDivAccueil($titreDivAccueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreDivAccueil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreDivAccueil', array());

        return parent::getTitreDivAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienDivAccueil($lienDivAccueil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienDivAccueil', array($lienDivAccueil));

        return parent::setLienDivAccueil($lienDivAccueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienDivAccueil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienDivAccueil', array());

        return parent::getLienDivAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexteDivAccueil($texteDivAccueil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexteDivAccueil', array($texteDivAccueil));

        return parent::setTexteDivAccueil($texteDivAccueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexteDivAccueil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexteDivAccueil', array());

        return parent::getTexteDivAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgDivAccueil($imgDivAccueil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgDivAccueil', array($imgDivAccueil));

        return parent::setImgDivAccueil($imgDivAccueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgDivAccueil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgDivAccueil', array());

        return parent::getImgDivAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDivAccueil($dateDivAccueil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDivAccueil', array($dateDivAccueil));

        return parent::setDateDivAccueil($dateDivAccueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDivAccueil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDivAccueil', array());

        return parent::getDateDivAccueil();
    }

}
