parameters:
#    ingetis_divindex.example.class: Ingetis\DivindexBundle\Example

services:
#    ingetis_divindex.example:
#        class: %ingetis_divindex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
